stages:
  - Build package
  - Publish package

variables:
  EVO_TEAM: noc
  EVO_APP: fortigate_api
  PYTHON_REPO: evo-pypi
  BUILD_RETENTION: 20

build-python-package:
  stage: Build package
  tags:
    - noc
  image: python:3.8-slim
  script: |
    pip install requests
    python setup.py sdist
  artifacts:
    expire_in: 1h
    paths:
      - dist

publish-python-package:
  stage: Publish package
  tags:
    - noc
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  image: releases-docker.jfrog.io/jfrog/jfrog-cli-v2
  script: |
    BUILD_NAME="${EVO_TEAM}::${EVO_APP}"
    BUILD_NUMBER="${CI_COMMIT_SHORT_SHA}"
    jfrog config add --artifactory-url ${RMS_URL} --user ${RMS_USER} --password ${RMS_PASSWORD}
    jfrog rt u "dist/(.*)" "${PYTHON_REPO}/${EVO_TEAM}/${EVO_APP}/{1}" --regexp \
            --build-name=${BUILD_NAME} \
            --build-number=${BUILD_NUMBER}
    jfrog rt bp ${BUILD_NAME} ${BUILD_NUMBER}
    jfrog rt bdi ${BUILD_NAME} --max-builds=${BUILD_RETENTION} --delete-artifacts
